---
# GLaDOS TCP Proxy - Kubernetes Deployment
# Forwards connections from K8s (NEWT tunnel) to external GPU server

apiVersion: v1
kind: Namespace
metadata:
  name: glados
  labels:
    app: glados

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: glados-proxy-config
  namespace: glados
data:
  # Change this to your GPU server's IP address
  GLADOS_TARGET: "192.168.1.100:5555"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: glados-proxy
  namespace: glados
  labels:
    app: glados-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glados-proxy
  template:
    metadata:
      labels:
        app: glados-proxy
    spec:
      containers:
      - name: glados-proxy
        image: glados-proxy:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5555
          protocol: TCP
          name: glados
        envFrom:
        - configMapRef:
            name: glados-proxy-config
        resources:
          requests:
            memory: "16Mi"
            cpu: "10m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        # Probes removed to prevent connection flooding on the single-threaded backend
        # livenessProbe:
        #   tcpSocket:
        #     port: 5555
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        # readinessProbe:
        #   tcpSocket:
        #     port: 5555
        #   initialDelaySeconds: 2
        #   periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: glados-proxy
  namespace: glados
  labels:
    app: glados-proxy
spec:
  type: ClusterIP
  ports:
  - port: 5555
    targetPort: 5555
    protocol: TCP
    name: glados
  selector:
    app: glados-proxy

---
# Optional: NodePort service for direct access (useful for testing)
# Uncomment if you need to access the proxy directly via NodePort
#
# apiVersion: v1
# kind: Service
# metadata:
#   name: glados-proxy-nodeport
#   namespace: glados
# spec:
#   type: NodePort
#   ports:
#   - port: 5555
#     targetPort: 5555
#     nodePort: 30555
#     protocol: TCP
#   selector:
#     app: glados-proxy
